Algoritmo "Preço dos CDs"
Var
   cor: caractere

Inicio
   escreva("Digite a cor do CD (verde,azul,amarelo ou vermelho): ")
   leia(cor)

se (cor = "verde") entao
  escreval ("preço: R$ 10,00")
  senao

  se (cor = "azul") entao
  escreva("Preço: R$ 20,00")
  fimse

  se (cor = "amarelo") entao
  escreva("Preço: R$ 30,00")
  fimse

  se (cor = "vermelho") entao
   escreva("Preço: R$ 40,00")
  fimse
fimse

FimAlgoritmo
